### ISSUE TITLE
Using the NavigationDrawer component causes Router to complain about "Detected multiple renderers"

### ISSUE THREAD

**Issue by v3gard** [equinor/fusion-components#1044]
I am using the NavigationDrawer component like this:

```
<Fusion.NavigationDrawer
                id="navigation-drawer-story"
                structure={props.structure}
                selectedId={props.activeProductGroup.id.toString()}
                onChangeSelectedId={props.onProductGroupChanged}
                onChangeStructure={() => {
                    console.log("structure changed");
                }}
            />
```

When the NavigationDrawer is initially loaded, I can hover my mouse between the rendered items without having errors in the Chrome Developer Tools console. However, after I have interacted with the NavigationDrawer (e.g. clicked the expand/retract button), whenever my cursor hovers over the items, or when I click one of the items to change the structure, the following is reported in the console:

```
react_devtools_backend.js:2557 Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at Router (http://localhost:3001/fusion.bundle.js:207385:30)
    at Root (http://localhost:3001/fusion.bundle.js:216868:71)
```

Currently I am unable to distinguish if this is due to a misconfiguration on my end, or if this is an underlying issue in the fusion-components framework. So far, I have only experienced this with the NavigationDrawer component. 

Other than the error message in the console, I do not experience any issues when using the NavigationDrawer.

**Comment by odinr** [comment]
this error is because of the overlay portal and React 17 (which recreates the fusion context container within).
The navigation drawer will be moved to react-components and the tooltip now uses tippy/popper.
