### ISSUE TITLE
usePopoverRef and useTooltipRef  multiple render error

### ISSUE THREAD

**Issue by olerichard** [equinor/fusion-components#1152]
When using popover/tooltop refs the hover and click effect triggers multiple "multiple renders" errors in the console. 
This happen each time you interact with the refs. 

 Ending up with a long list like with these. 
 
![image](https://user-images.githubusercontent.com/16989176/122886160-fca4ef00-d33f-11eb-98a5-2bd63e48b1e5.png)

**Comment by odinr** [comment]
this is a mix of react 17 createPortal and the rendering of overlay, this component is recreated.

[popper](https://equinor.github.io/fusion-react-components/?path=/docs/examples-popover--component)

[tooltip](https://equinor.github.io/fusion-react-components/?path=/docs/examples-tooltip--component)
