### ISSUE TITLE
Change request: Make the narrower scroll bars optional

### ISSUE THREAD

**Issue by denektenina** [equinor/fusion-components#1418]
Not sure if I'm posting this in the right repo (please notify me if not): It seems that fusion-apps have a different type of scroll bars than the default browser scrollbars. I found some references to a package called overlayscrollbars, but I'm not sure if this is what is used. 

In our fusion-app we have been asked if it is possible to have wider scroll bars, because some users need to be able to click it to navigate.

Since this is actually configured to not be like the default browser scroll in fusion on purpose, it would be nice if this feature is possible to toggle off when using fusion.

**Comment by AndrejNikolicEq** [comment]
This will be a feature that will come with global containers.

**Comment by odinr** [comment]
@AndrejNikolicEq , the scrollbar setting should be an css variable,
for the component, the component mention is deprecated, please use EDS
