### ISSUE TITLE
ModalSidesheet does not have a Scrim in local development in version 2.5.27

### ISSUE THREAD

**Issue by v3gard** [equinor/fusion-components#1512]
When a `ModalSidesheet` is used in version 2.5.27 (with fusion-cli 3.0.0-beta.17), the Scrim is no longer visible. And it is not possible to close the ModalSidesheet by clicking "outside" of the component. It can still be closed, but only via the close button in the sidesheet.

# Demo
![sidesheet_scrim_bug](https://user-images.githubusercontent.com/343078/172838903-ef5789e9-882e-46be-876d-fb3e4029520b.gif)

**Comment by odinr** [comment]
this is not a bug within the fusion-components, but with fusion-cli
