### ISSUE TITLE
DataTable (legacy) sticky headers doesn't work as overflow is set to auto

### ISSUE THREAD

**Issue by v3gard** [equinor/fusion-components#1540]
In large data sets, I expect the column header of the `DataTable` to be sticky as I scroll down. Currently, it doesn't do this.

|Expected behavior|Actual behavior|
|-|-|
|![headers_not_sticky_fixed](https://user-images.githubusercontent.com/343078/193809075-1e77ad66-f400-4f7e-ad73-03b1750f0095.gif)|![headers_not_sticky_error](https://user-images.githubusercontent.com/343078/193809099-0a562e04-d69a-49b6-94ff-c83164e5649e.gif)||

# Components used
* Fusion DataTable (from fusion-components 2.5.28)

# Possible solution
You can solve this error by clearing the `overflow: auto` style, e.g. 
![image](https://user-images.githubusercontent.com/343078/193809316-a2e95273-8c5a-49cc-976a-bf1a1e07771e.png)

However, as the DataTable component is considered legacy, is it recommended to move to ag-grid instead?

**Comment by eikeland** [comment]
Created a fix with your suggestion, But you should look to change to AG-Grid since DataTable will be deprecated in near future.
