### ISSUE TITLE
NavigationDrawer is broken in version 2.10.1

### ISSUE THREAD

**Issue by v3gard** [equinor/fusion-components#1606]
With the newest version, fusion-components `2.10.1`, it seems that `<NavigationDrawer/>` is broken. When I click a row in the component, the `onChangeSelectedId` event doesn't fire, and thus doesn't invoke my callback function.

We typically use `NavigationDrawer` like this. This code has seen no changes for the past 20 months in our repository:

```ts
<Fusion.NavigationDrawer
    id="navigation-drawer-story"
    structure={props.productGroupStructure}
    selectedId={selectedId}
    onChangeSelectedId={props.onProductGroupChanged}
    onChangeStructure={() => {
        /* Empty because we control structure change from the parent function */
    }}
/>
```

The version we're currently using, fusion-components `2.9.3`, seems to work. Perhaps #1596 is the PR that introduced the bug?

# Demo
|Before (2.9.3)|After (2.10.1)|
|-|-|
|![before](https://user-images.githubusercontent.com/343078/220575581-b6a531c2-9b56-4f0d-a1d8-fe2f2022015d.gif)|![after](https://user-images.githubusercontent.com/343078/220576220-54512b02-471a-4b87-ac78-2e637592b257.gif)|

**Comment by v3gard** [comment]
This issue is still present in the [newest release](https://www.npmjs.com/package/@equinor/fusion-components) on npmjs, `2.10.3`. The newest version here on Github appears to be `2.10.2`. This is a bit confusing.

|Github|npmjs|
|-|-|
|![image](https://user-images.githubusercontent.com/343078/221879143-44d2c2c6-53c8-4b44-b79f-24cd4fb193c7.png)|![image](https://user-images.githubusercontent.com/343078/221879385-ce266411-32c4-4b40-8dea-c8b1fd2ba78a.png)|

**Comment by v3gard** [comment]
NavigationDrawer is still broken in 2.10.5.

**Comment by vft-equinor** [comment]
Still an issue in `2.10.6`.

**Comment by v3gard** [comment]
We got a warning from Dependabot today. We cannot solve[ a security vulnerability in the yaml package](https://security.snyk.io/vuln/SNYK-JS-YAML-5458867) because we're required to use an older version of fusion-components due to the issue mentioned above.

![image](https://user-images.githubusercontent.com/343078/234195344-a722c3d9-f359-4b71-8e4e-eb057e236571.png)

Probably something to discuss on the next architecture meeting.

**Comment by vft-equinor** [comment]
Still an issue in `2.10.8`.

**Comment by vft-equinor** [comment]
Still an issue in `2.11.0`.

**Comment by v3gard** [comment]
This can be closed from our end as we've removed the `<NavigationDrawer>` component from our code base.
