### ISSUE TITLE
Banner not displaying correctly

### ISSUE THREAD

**Issue by sandves** [equinor/fusion-components#270]
Current:
![image](https://user-images.githubusercontent.com/3788207/74147837-58b41b00-4c04-11ea-846f-9245f0157a3f.png)

Expected:
![image](https://user-images.githubusercontent.com/3788207/74147859-65387380-4c04-11ea-9d7a-836ae6d7d23b.png)

I believe this bug was introduced by #243:
https://github.com/equinor/fusion-components/blob/e47764d2ce4958c777626f89a08ab95752703153/src/components/feedback/Banner/styles.less#L63

Why was this introduced, and how can we fix it @MartinForre ?

**Comment by MartinForre** [comment]
Fixed by #277
