### ISSUE TITLE
Suggestion: Stop using big nested objects as props

### ISSUE THREAD

**Issue by nicholasdalhaug** [equinor/fusion-components#856]
For example [the Navigation Drawer](https://equinor.github.io/fusion-components/?path=/story/general-navigation-drawer--default) has its content described by [a big nested object](https://github.com/equinor/fusion-components/blob/72dc7c64f64b9c6cbfc5a9af4e46d49286fc822f/src/components/general/NavigationDrawer/__stories__/NavigationDrawer.stories.tsx#L8). It uses [switch statements](https://github.com/equinor/fusion-components/blob/72dc7c64f64b9c6cbfc5a9af4e46d49286fc822f/src/components/general/NavigationDrawer/utils.tsx#L26) to figure out what components to use. 

I suggest to rather write [the drawer](https://github.com/equinor/fusion-components/blob/72dc7c64f64b9c6cbfc5a9af4e46d49286fc822f/src/components/general/NavigationDrawer/__stories__/NavigationDrawer.stories.tsx#L118) to take in `children` as props and maybe change behaviour of content by sending props to children as [exemplified here](https://stackoverflow.com/a/32371612/13075037).

**Comment by odinr** [comment]
We think this might be an breaking change and a lot of work for something that is working. We see the referred code is a better solution and are open for change. You could open a PR on this, maybe as a new component.

**Comment by odinr** [comment]
navigation drawer will be rewritten in fusion-react-components using remux pages
